"""RDL -> editable Modo scene, using a native parser and explicit conversion notices."""
import math,uuid
from pathlib import Path
IDENTITY=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]
pending=None

def transform(point,matrix):
 return [sum(point[j]*matrix[j*4+i] for j in range(3))+matrix[12+i] for i in range(3)]

def product(a,b):return [sum(a[row*4+k]*b[k*4+col] for k in range(4)) for row in range(4) for col in range(4)]

def graph(root,objects,base,warnings):
 from . import nodes,shader_library
 result={'version':1,'root':root,'nodes':{}}
 def visit(name):
  if name in result['nodes']:return
  if len(result['nodes'])>=1000:raise ValueError('Imported material exceeds node limit')
  record=objects[name];kind=record['type'];schema=nodes.specs(kind)
  node={'type':kind,'parameters':{},'inputs':{},'position':[len(result['nodes'])*180,0]};result['nodes'][name]=node
  for key,spec in schema.items():
   if key not in record.get('attributes',{}):continue
   value=record['attributes'][key]
   binding=record.get('bindings',{}).get(key)
   target=binding or (value if spec['type']=='SceneObject*' and isinstance(value,str) else None)
   if target:
    if target not in objects or not nodes.connectable(kind,key):
     warnings.append(name+': unsupported object reference '+key);continue
    visit(target);node['inputs'][key]=target
    if spec['type']=='SceneObject*':continue
   if key in record.get('files',[]) and isinstance(value,str) and value:
    path=Path(value);value=str((base/path).resolve()) if not path.is_absolute() else str(path)
    if not Path(value).is_file() and '<UDIM>' not in value:warnings.append('Missing asset: '+value)
   try:node['parameters'][key]=shader_library.typed(value,spec)
   except ValueError as exc:warnings.append(name+' / '+key+': '+str(exc))
 visit(root)
 return nodes.validate(result)

def plan(document,path):
 if document.get('version')!=1 or not isinstance(document.get('objects'),list):raise ValueError('Invalid RDL conversion document')
 objects={v['name']:v for v in document['objects']};warnings=[];meshes=[];materials={};cameras=[];lights=[]
 base=Path(path).resolve().parent
 from . import shader_library
 variables=next((v.get('attributes',{}) for v in objects.values() if v['type']=='SceneVariables'),{})
 layer=objects.get(variables.get('layer'),next((v for v in objects.values() if v['type']=='Layer'),{})).get('attributes',{})
 assignments={}
 for geometry,part,material in zip(layer.get('geometries',[]),layer.get('parts',[]),layer.get('surface_shaders',[])):
  assignments[(geometry,part)]=material
 for record in objects.values():
  if record['type'] in shader_library.catalog():
   try:materials[record['name']]=graph(record['name'],objects,base,warnings)
   except (ValueError,KeyError) as exc:warnings.append(record['name']+': material graph could not be converted: '+str(exc))
 def mesh(record,matrix=None,label=None,assignment_owner=None):
  a=record.get('attributes',{});vertices=a.get('vertex_list_0',a.get('vertex_list',[]));counts=a.get('face_vertex_count',[]);indices=a.get('vertices_by_index',[])
  if not vertices or not counts:return
  if any(type(n)!=int or n<3 for n in counts) or sum(counts)!=len(indices):raise ValueError('Invalid face counts: '+record['name'])
  if any(type(i)!=int or i<0 or i>=len(vertices) for i in indices):raise ValueError('Invalid point index: '+record['name'])
  if any(len(v)!=3 or any(not math.isfinite(x) for x in v) for v in vertices):raise ValueError('Invalid vertex coordinates')
  matrix=matrix or a.get('node_xform',IDENTITY)
  if len(matrix)!=16 or any(not math.isfinite(x) for x in matrix):raise ValueError('Invalid mesh transform')
  tags=[assignments.get((assignment_owner or record['name'],''),assignments.get((record['name'],'')))]*len(counts)
  offset=0
  for part,count in zip(a.get('part_list',[]),a.get('part_face_count_list',[])):
   for face in a.get('part_face_indices',[])[offset:offset+count]:
    if not 0<=face<len(tags):raise ValueError('Invalid material part face index')
    tags[face]=assignments.get((assignment_owner or record['name'],part),assignments.get((record['name'],part),tags[face]))
   offset+=count
  uv=a.get('uv_list',[])
  if uv and len(uv) not in (len(vertices),len(indices)):warnings.append(record['name']+': unsupported UV interpolation');uv=[]
  faces=[];offset=0
  for count in counts:faces.append(indices[offset:offset+count]);offset+=count
  meshes.append({'name':label or record['name'],'vertices':[transform(v,matrix) for v in vertices],'faces':faces,'uv':uv,'tags':tags,'subd':a.get('is_subd',False)})
  if a.get('normal_list'):warnings.append(record['name']+': authored normals are regenerated by Modo')
  if a.get('subd_crease_indices') or a.get('subd_corner_indices'):warnings.append(record['name']+': subdivision crease/corner weights are not imported')
  if a.get('vertex_list_1'):warnings.append(record['name']+': imported the first deformation sample only')
 referenced={name for v in objects.values() if v['type']=='RdlInstancerGeometry' for name in v.get('attributes',{}).get('references',[])}
 geometry_sets={name for v in objects.values() if v['type']=='GeometrySet' for name in v.get('attributes',{}).get('geometries',[])}
 for record in objects.values():
  kind=record['type'];a=record.get('attributes',{})
  if kind=='RdlMeshGeometry':
   if record['name'] not in referenced or record['name'] in geometry_sets:mesh(record)
  elif kind=='RdlInstancerGeometry':
   refs=a.get('references',[]);transforms=a.get('xform_list',[])
   if a.get('method')!=2 or len(refs)!=1 or objects.get(refs[0],{}).get('type')!='RdlMeshGeometry':warnings.append(record['name']+': unsupported instancer method or prototype');continue
   proto=objects[refs[0]]
   for index,xform in enumerate(transforms):
    mat=product(xform,a.get('node_xform',IDENTITY))
    if a.get('use_reference_xforms',True):mat=product(proto['attributes'].get('node_xform',IDENTITY),mat)
    mesh(proto,mat,record['name']+' / '+str(index),record['name'])
   warnings.append(record['name']+': instances expanded to editable meshes; per-instance primitive attributes are not imported')
  elif kind in ('PerspectiveCamera','OrthographicCamera'):cameras.append(record)
  elif kind in ('SphereLight','DistantLight','RectLight','SpotLight'):lights.append(record)
  elif kind.endswith('Geometry') or kind.endswith('Light') or kind.endswith('LightFilter'):
   warnings.append(record['name']+': '+kind+' is not converted to Modo')
 if layer.get('displacements') and any(layer['displacements']):warnings.append('Layer displacement assignments are not imported')
 warnings.append('Imported a static scene. Motion samples, render outputs, light linking, visibility sets and environment controls require review. Modo light intensity/shape matching is approximate.')
 return dict(meshes=meshes,materials=materials,cameras=cameras,lights=lights,warnings=list(dict.fromkeys(warnings)),variables=variables,source=str(path))

def apply(data):
 import modo,lx
 from . import properties
 scene=modo.Scene();created=[];warnings=list(data['warnings']);tags={}
 previous_camera=scene.renderCamera;previous_selection=list(scene.selected)
 try:
  for name,graph in data['materials'].items():
   tag='RDL_'+uuid.uuid4().hex[:12];tags[name]=tag
   mask=scene.addItem('mask',name='RDL '+name);created.append(mask);mask.setParent(scene.renderItem,0)
   mask.channel('ptyp').set('Material');mask.channel('ptag').set(tag)
   material=scene.addItem('advancedMaterial',name='MoonShine '+name);created.append(material);material.setParent(mask,0)
   properties.write(material,{'shader':'DwaBaseMaterial','native_shader':graph['nodes'][graph['root']]['type'],'node_graph':graph,'node_override':True})
  for record in data['meshes']:
   item=scene.addItem('mesh',name=record['name']);created.append(item)
   with item.geometry as geo:
    vertices=[geo.vertices.new(v) for v in record['vertices']]
    uv=geo.vmaps.addUVMap('RDL UV') if record['uv'] else None;offset=0
    for face_index,face in enumerate(record['faces']):
     polygon=geo.polygons.new([vertices[i] for i in face],polyType=lx.symbol.iPTYP_SUBD if record['subd'] else lx.symbol.iPTYP_FACE)
     if record['tags'][face_index] in tags:polygon.materialTag=tags[record['tags'][face_index]]
     if uv:
      for corner,index in enumerate(face):polygon.setUV(record['uv'][index if len(record['uv'])==len(vertices) else offset+corner],corner,uv)
     offset+=len(face)
  def pose(item,attrs):
   raw=attrs.get('node_xform',IDENTITY);matrix=modo.Matrix4([raw[i:i+4] for i in range(0,16,4)])
   scale=list(matrix.scale())
   rotation=modo.Matrix4([[(raw[row*4+col]/scale[row] if row<3 and col<3 and scale[row] else raw[row*4+col]) for col in range(4)] for row in range(4)])
   item.position.set(raw[12:15]);item.rotation.set(rotation.asEuler());item.scale.set(scale)
  for record in data['cameras']:
   item=scene.addItem('camera',name=record['name']);created.append(item);a=record['attributes'];pose(item,a)
   item.channel('focalLen').set(a.get('focal',30)*.001);item.channel('apertureX').set(a.get('film_width_aperture',24)*.001)
   if record['type']=='OrthographicCamera':item.channel('projType').set('ortho');warnings.append(record['name']+': orthographic framing needs review')
   if data['variables'].get('camera')==record['name']:scene.renderCamera=item
  for record in data['lights']:
   kind={'SphereLight':'pointLight','DistantLight':'sunLight','RectLight':'areaLight','SpotLight':'spotLight'}[record['type']]
   item=scene.addItem(kind,name=record['name']);created.append(item);a=record['attributes'];pose(item,a)
   item.channel('radiance').set(float(a.get('intensity',1))*2**float(a.get('exposure',0)))
   if item.material:item.material.channel('lightCol').set(tuple(a.get('color',[1,1,1])))
  scene.select([v for v in created if v.type=='mesh'])
  return '%d meshes, %d cameras, %d lights, %d materials imported.\n\n%s'%(len(data['meshes']),len(data['cameras']),len(data['lights']),len(tags),'\n'.join(warnings))
 except Exception:
  # Conversion validates before editing; clean up created items on host failures.
  for item in reversed(created):
   try:scene.removeItem(item)
   except Exception:pass
  try:scene.renderCamera=previous_camera;scene.select(previous_selection)
  except Exception:pass
  raise
